name: Land Scraper Daily

on:
  schedule:
    - cron: "0 12 * * 1-5" # 12:00 UTC = 15:00 Riga (summer)
  workflow_dispatch:

permissions:
  contents: write # required for pushing changes

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # fetch full history (required for rebase)

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run scraper
        run: npx ts-node src/scrapeLands.ts
        env:
          EMAIL_USER_LAND: ${{ secrets.EMAIL_USER_LAND }}
          EMAIL_PASS_LAND: ${{ secrets.EMAIL_PASS_LAND }}
          RECIPIENT_EMAIL_LAND: ${{ secrets.RECIPIENT_EMAIL_LAND }}
          BCC_EMAIL_LAND: ${{ secrets.BCC_EMAIL_LAND }}

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lands-scraped.xlsx

          if git diff --staged --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Update lands data - $(date +'%Y-%m-%d %H:%M')"

            # Ensure remote changes are pulled before pushing
            git fetch origin main
            git rebase origin/main || (echo "⚠️ Rebase conflict — keeping local version" && git rebase --abort && git pull --strategy=ours origin main)

            git push origin main
          fi
